CREATE TABLE IF NOT EXISTS `users`(
    `user_id` VARCHAR(14) NOT NULL,
    `user_name` VARCHAR(15) NOT NULL,
    `twitter_handle` VARCHAR(15) NOT NULL,
    `user_email` VARCHAR(320) NOT NULL,
    `user_password` VARCHAR (128) NOT NULL,
    `profile_image` VARCHAR(255) NOT NULL,
    `header_image` VARCHAR(255) NOT NULL,
    `time_stamp` BIGINT,
    INDEX users_username_password_idx (`user_name`, `user_password`),
    INDEX users_email_password_idx (`user_email`, `user_password`),
    INDEX users_timestamp_idx (`time_stamp`),
    PRIMARY KEY (`user_id`)
);

CREATE TABLE IF NOT EXISTS `tweets` (
    `tweet_id` VARCHAR(14) NOT NULL,
    `user_id` VARCHAR(14) NOT NULL,
    `reply_id` VARCHAR(14),
    `content` VARCHAR(280),
    `media` VARCHAR(1020),
    `likes` INT,
    `user_name` VARCHAR(15) NOT NULL,
    `twitter_handle` VARCHAR(15) NOT NULL,
    `profile_image` VARCHAR(255) NOT NULL,
    `retweet_id` VARCHAR(14),
    `retweet_user_id` VARCHAR(14),
    `retweet_twitter_handle` VARCHAR(15),
    `quote_tweet_id` VARCHAR(14),
    `retweet_quoute_count` INT,
    `time_stamp` BIGINT,
    INDEX tweets_userid_media_idx (`user_id`, `media`),
    INDEX tweets_replyid_idx (`reply_id`),
    INDEX tweets_quoteid_idx (`quote_tweet_id`),
    INDEX tweets_retweetid_idx (`retweet_user_id`),
    INDEX tweets_userId_retweetId_idx (`user_id`, `retweet_id`),
    INDEX tweets_retweetuserId_retweetId_idx (`retweet_user_id`, `retweet_id`),
    PRIMARY KEY (`tweet_id`)
);

CREATE TABLE IF NOT EXISTS `follows` (
    `follower_id` VARCHAR(14) NOT NULL,
    `followee_id` VARCHAR(14) NOT NULL,
    `follower_user_name` VARCHAR(15) NOT NULL,
    `follower_twitter_handle` VARCHAR(15) NOT NULL,
    `follower_profile_image` VARCHAR(255) NOT NULL,
    `followee_user_name` VARCHAR(15) NOT NULL,
    `followee_twitter_handle` VARCHAR(15) NOT NULL,
    `followee_profile_image` VARCHAR(255) NOT NULL,
    `time_stamp` BIGINT,
    INDEX follows_follower_followee_idx(`follower_id`,`followee_id`),
    PRIMARY KEY (`follower_id`, `followee_id`)
);

CREATE TABLE IF NOT EXISTS `likedTweets` (
    `liker_id` VARCHAR(14) NOT NULL,
    `tweet_id` VARCHAR(14) NOT NULL,
    `user_id` VARCHAR(14) NOT NULL,
    `reply_id` VARCHAR(14),
    `content` VARCHAR(280),
    `media` VARCHAR(1020),
    `likes` INT,
    `user_name` VARCHAR(15) NOT NULL,
    `twitter_handle` VARCHAR(15) NOT NULL,
    `profile_image` VARCHAR(255) NOT NULL,
    `liker_user_name` VARCHAR(15) NOT NULL,
    `liker_twitter_handle` VARCHAR(15) NOT NULL,
    `liker_profile_image` VARCHAR(255) NOT NULL,
    `retweet_id` VARCHAR(14),
    `retweet_user_id`VARCHAR(14),
    `retweet_twitter_handle` VARCHAR(15),
    `quote_tweet_id` VARCHAR(14),
    `retweet_quoute_count` INT,
    `time_stamp` BIGINT,
    INDEX tweets_userid_media_idx (`user_id`, `media`),
    INDEX tweets_replyid_idx (`reply_id`),
    INDEX tweets_quoteid_idx (`quote_tweet_id`),
    INDEX tweets_retweetid_idx (`retweet_user_id`),
    INDEX tweets_userId_retweetId_idx (`user_id`, `retweet_id`),
    INDEX tweets_retweetuserId_retweetId_idx (`retweet_user_id`, `retweet_id`),
    PRIMARY KEY (`tweet_id`, `liker_id`)
);